on:
  workflow_call:
    inputs:
      packages:
        description: Packages (comma-separated values)
        type: string
        default: ${{ github.workflow }}
      test:
        description: Test
        type: boolean
      force:
        description: Force update
        type: boolean

jobs:
  update:
    name: Update ${{ github.workflow }}
    runs-on: windows-latest
    timeout-minutes: 20

    env:
      # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
      au_version: release

    steps:
      - name: Set up git
        if: ${{ !inputs.test }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git config --global core.safecrlf false

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install AU
        run: |
          git clone -q https://github.com/Thilas/au.git "$env:TEMP/au"
          . "$env:TEMP/au/scripts/Install-AU.ps1" $env:au_version

      - name: Update packages
        id: updates
        run: |
          $names = $env:packages -replace " ","" -split ","
          $force = $env:force -eq "true"
          [array] $packages = ./update_all.ps1 -Name $names -Force:$force | ForEach-Object {
            $_ | ConvertTo-Json -Compress
          }
          $packages = ConvertTo-Json $packages -Compress
          "Packages = $packages"
          "packages=$packages" >> $env:GITHUB_OUTPUT
        env:
          packages: ${{ inputs.packages }}
          force: ${{ inputs.test || inputs.force }}
          github_user_repo: ${{ github.repository }}
          github_api_key: ${{ secrets.GITHUB_TOKEN }}
          au_push: ${{ !inputs.test }}
          api_key: ${{ secrets.CHOCOLATEY_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish report
        if: always() && hashFiles('report.md')
        run: Get-Content "report.md" >> $env:GITHUB_STEP_SUMMARY

      - name: Prepare Packages artifact
        if: always() && hashFiles('**/*.nupkg')
        run: |
          New-Item Packages -ItemType Directory
          Get-ChildItem *.nupkg -Recurse | Move-Item -Destination Packages

      - name: Upload Packages artifact
        if: always() && hashFiles('Packages/*.nupkg')
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: Packages/*.nupkg

    outputs:
      updates: ${{ steps.updates.outputs.packages }}

  test:
    needs: [update]
    if: needs.update.outputs.updates != 'null'

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.update.outputs.updates) }}
        os:
          - windows-2019
          # - windows-2022

    name: Test ${{ fromJSON(matrix.package).name }} ${{ fromJSON(matrix.package).version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    env:
      package_name: ${{ fromJSON(matrix.package).name }}
      package_version: ${{ fromJSON(matrix.package).version }}

    steps:
      - name: Remove package if needed
        run: |
          if (choco list -r $env:package_name) {
            choco uninstall -y --no-progress $env:package_name
          }

      - name: Download Packages artifact
        uses: actions/download-artifact@v3
        with:
          name: Packages

      - name: Install package
        run: |
          $debug = if ($env:debug) { "--verbose --debug" }
          choco install -y --no-progress $env:package_name --version $env:package_version --source "'.;https://community.chocolatey.org/api/v2/'" $debug
          if ($LASTEXITCODE -in 1641, 3010) { exit 0 }
        env:
          debug: ${{ runner.debug }}
        timeout-minutes: 10

      - name: Determine package information path
        id: information
        run: |
          $path = Join-Path $env:ChocolateyInstall ".chocolatey/$env:package_name.$env:package_version"
          $path = $path -replace "\\", "/"
          Get-ChildItem $path
          "path=$path" >> $env:GITHUB_OUTPUT

      - name: Upload Information artifact
        uses: actions/upload-artifact@v3
        with:
          name: Information ${{ env.package_name }} ${{ env.package_version }} on ${{ matrix.os }}
          path: ${{ steps.information.outputs.path }}

      - name: Uninstall package
        # AirServer requires Wireless-Networking while uninstalling, feature not installed on GitHub agents
        if: env.package_name != 'airserver'
        run: |
          $debug = if ($env:debug) { "--verbose --debug" }
          choco uninstall -y --no-progress $env:package_name $debug
          if ($LASTEXITCODE -in 1605, 1614, 1641, 3010) { exit 0 }
        env:
          debug: ${{ runner.debug }}
        timeout-minutes: 10

      - name: Take failure screenshot
        if: failure()
        run: |
          choco install -y --no-progress nircmd
          nircmd savescreenshotfull desktop.png

      - name: Upload failure screenshot into Information artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Information ${{ env.package_name }} ${{ env.package_version }} on ${{ matrix.os }}
          path: desktop.png
