name: aaa

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]
    paths:
      - .github/workflows/aaa.yml

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          $debug = if ($env:debug) { "--verbose --debug" }
          choco install -y -i --no-progress ilspy nircmd $debug
          if ($LASTEXITCODE -in 1641, 3010) { exit 0 }
          nircmd savescreenshotfull desktop.0.0.install.png
        env:
          debug: ${{ runner.debug }}

      - name: Tests
        run: ./Invoke-TestCases.ps1
        env:
          debug: ${{ runner.debug }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: Screenshots
          path: desktop.*.png
