name: aaa

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]
    paths:
      - .github/workflows/aaa.yml

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          $debug = if ($env:debug) { "--verbose --debug" }
          choco install -y -i --no-progress ilspy $debug
          if ($LASTEXITCODE -in 1641, 3010) { exit 0 }
        env:
          debug: ${{ runner.debug }}

      - name: Tests
        run: ./Invoke-TestCases.ps1
        env:
          debug: ${{ runner.debug }}
          test_cases: |
            - Start program
              $sw = [System.Diagnostics.Stopwatch]::StartNew()
              Start-Process ILSpy -LoadUserProfile -NoNewWindow -PassThru | Tee-Object -Variable p
              while (!($p | Where-Object MainWindowHandle -NE 0)) {
                if ($sw.ElapsedMilliseconds -gt 30000) {
                  throw "Process start timed out."
                }
                Start-Sleep -Milliseconds 100
                Get-Process ILSpy | Tee-Object -Variable p
              }
              "Started in {0}ms" -f $sw.ElapsedMilliseconds
            - Close program
              Get-Process ILSpy | Tee-Object -Variable p
              #$p | Should -Not -BeNullOrEmpty
              $sw = [System.Diagnostics.Stopwatch]::StartNew()
              $p | ForEach-Object CloseMainWindow
              Wait-Process ILSpy -Timeout 30
              "Closed in {0}ms" -f $sw.ElapsedMilliseconds
