name: ilspy

on:
  pull_request:         # Automatic test
    types: [opened, reopened, synchronize]
    branches: [master]
    paths:
      - .github/workflows/.common.yml
      # - .github/workflows/ilspy.yml
      - ilspy/**
      - Common.ps1
      - update_all.ps1
  schedule:
    - cron: 0 4 * * *   # Scheduled test
    - cron: 35 0-23/6 * * * # Scheduled update
  workflow_dispatch:    # Manual run
    inputs:
      type:
        description: Type
        type: choice
        required: true
        default: Test
        options:
          - Force update
          - Test
          - Update

jobs:
  job:
    name: ${{ inputs.type || (github.event_name == 'pull_request' || github.event.schedule == '0 4 * * *') && 'Test' || 'Update' }}
    uses: ./.github/workflows/.common.yml
    with:
      test: ${{ github.event_name == 'pull_request' || github.event.schedule == '0 4 * * *' || inputs.type == 'Test' }}
      force: ${{ inputs.type == 'Force update' }}
      test_cases: |
        - Start ILSpy
          Start-Process ILSpy -LoadUserProfile -NoNewWindow
          $sw = [System.Diagnostics.Stopwatch]::StartNew()
          while ($sw.ElapsedMilliseconds -lt 30000) {
            if ($p = Get-Process ILSpy* | Where-Object MainWindowHandle -NE 0) {
              $p, ("Started in {0}ms" -f $sw.ElapsedMilliseconds)
              return
            }
            Start-Sleep -Milliseconds 100
          }
          throw "Process start timed out."
        - Close ILSpy
          Get-Process ILSpy* | Tee-Object -Variable p
          $p | Should -Not -BeNullOrEmpty
          $sw = [System.Diagnostics.Stopwatch]::StartNew()
          $p | ForEach-Object CloseMainWindow
          Wait-Process ILSpy* -Timeout 30
          "Closed in {0}ms" -f $sw.ElapsedMilliseconds
    secrets: inherit
