name: plezy

on:
  pull_request:         # Automatic test
    types: [opened, reopened, synchronize]
    branches: [master]
    paths:
      - .github/workflows/.common.yml
      - .github/workflows/plezy.yml
      - plezy/**
      - Common.ps1
      - test.ps1
      - update_all.ps1
  schedule:
    - cron: 0 4 * * *   # Scheduled test
    - cron: 45 3-23/6 * * * # Scheduled update
  workflow_dispatch:    # Manual run
    inputs:
      type:
        description: Type
        type: choice
        required: true
        default: Test
        options:
          - Force update
          - Test
          - Update

jobs:
  job:
    name: ${{ inputs.type || (github.event_name == 'pull_request' || github.event.schedule == '0 4 * * *') && 'Test' || 'Update' }}
    uses: ./.github/workflows/.common.yml
    with:
      test: ${{ github.event_name == 'pull_request' || github.event.schedule == '0 4 * * *' || inputs.type == 'Test' }}
      force: ${{ inputs.type == 'Force update' }}
      test_cases: |
        - Start program
          # Install latest Vulkan Runtime
          Invoke-RestMethod -Uri 'https://vulkan.lunarg.com/sdk/files.json' -UseBasicParsing
          | ForEach-Object { $_.windows.PSObject.Properties }
          | Where-Object { $_.Value.acl -eq 'public' }
          | Sort-Object -Descending { $_.Name -as [version] }
          | Select-Object -First 1
          | ForEach-Object {
              'Installing Vulkan Runtime {0} released on {1}...' -f $_.Name, $_.Value.release_date
              $file = $_.Value.files | Where-Object { $_.name -eq 'Runtime' -and $_.acl -eq 'public' -and $_.uploaded }
              if (!$file -or $file -is [array]) {
                  Write-Error 'Runtime installer not found.'
              }
              $url = 'https://sdk.lunarg.com/sdk/download/{0}/windows/{1}' -f @(
                  [System.Web.HttpUtility]::UrlEncode($_.Name)
                  [System.Web.HttpUtility]::UrlEncode($file.file_name)
              )
              $installer = Join-Path $PSScriptRoot $file.file_name
              try {
                  [System.Net.WebClient]::new().DownloadFile($url, $installer)
                  $fileHash = Get-FileHash $installer -Algorithm SHA256
                  if ($fileHash.Hash -ne $file.sha) {
                      Write-Error 'Runtime installer does not match expected hash.'
                  }
                  $process = Start-Process -FilePath $installer -ArgumentList '/S' -PassThru -Wait
                  if ($process.ExitCode -ne 0) {
                      Write-Error 'Runtime installer failed.'
                  }
              } finally {
                  Remove-Item $installer -ErrorAction SilentlyContinue
              }
          }
          Start-Program Plezy -Shortcut
        - Close program
          Close-Program plezy
    secrets: inherit
