name: procexp

on:
  pull_request:         # Automatic test
    types: [opened, edited, reopened, synchronize]
    branches: [master]
    paths:
      - .github/workflows/.new.yml
      - .github/workflows/procexp.yml
      - procexp/**
      - Common.ps1
      - test_all.ps1
      - update_vars.ps1
  push:                 # Automatic update
    branches: [master]
    paths:
      - .github/workflows/.new.yml
      - .github/workflows/procexp.yml
      - procexp/**
      - Common.ps1
      - update_all.ps1
      - update_vars.ps1
  schedule:
    - cron: 0 4 * * *   # Scheduled test
    - cron: 5 */6 * * * # Scheduled update
  workflow_dispatch:    # Manual run
    inputs:
      type:
        description: Type
        type: choice
        required: true
        default: Test
        options:
          - Force update
          - Test
          - Update

jobs:
  job:
    name: ${{ fromJSON(format('{{"pull_request":"Test","push":"Update","schedule":"{0}","workflow_dispatch":"{1}"}', fromJSON('{"0 4 * * *":"Test","5 */6 * * *":"Update"}')[github.event.schedule], inputs.type))[github.event_name] }}
    uses: ./.github/workflows/.new.yml
    with:
      test: ${{ github.event_name == 'pull_request' || github.event.schedule == '0 4 * * *' || inputs.type == 'Test' }}
      force: ${{ inputs.type == 'Force update' }}
    secrets: inherit
