on:
  workflow_call:
    inputs:
      updates:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(inputs.updates) }}
        os:
          - windows-2019
          # - windows-2022

    name: ${{ fromJSON(matrix.package).name }} ${{ fromJSON(matrix.package).version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    env:
      PackageName: ${{ fromJSON(matrix.package).name }}
      PackageVersion: ${{ fromJSON(matrix.package).version }}

    steps:
      - name: Remove package if installed
        run: |
          if (choco list -r --local `"$Env:PackageName`") {
            choco uninstall -y `"$Env:PackageName`"
          }

      - name: Download Packages artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: Packages

      - name: Install package
        run: |
          choco install -y `"$Env:PackageName`" --version `"$Env:PackageVersion`" --source `"'.;https://community.chocolatey.org/api/v2/'`" --force --debug
          if ($LASTEXITCODE -in 1641, 3010) { exit 0 }
        timeout-minutes: 10

      - name: Determine package information path
        id: information
        run: |
          $path = Join-Path $Env:ChocolateyInstall ".chocolatey/$Env:PackageName.$Env:PackageVersion"
          $path = $path -replace '\\', '/'
          Get-ChildItem $path
          "path=$path" >> $Env:GITHUB_OUTPUT

      - name: Upload Information artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Information ${{ fromJSON(matrix.package).name }} ${{ fromJSON(matrix.package).version }} on ${{ matrix.os }}
          path: ${{ steps.information.outputs.path }}

      - name: Uninstall package
        # AirServer requires Wireless-Networking while uninstalling, feature not installed on GitHub agents
        if: env.PackageName != 'airserver'
        run: |
          choco uninstall -y `"$Env:PackageName`" --debug
          if ($LASTEXITCODE -in 1605, 1614, 1641, 3010) { exit 0 }
        timeout-minutes: 10

      - name: Take failure screenshot
        if: failure()
        run: |
          choco install nircmd
          nircmd savescreenshotfull desktop.png

      - name: Upload failure screenshot into Information artifact
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Information ${{ fromJSON(matrix.package).name }} ${{ fromJSON(matrix.package).version }} on ${{ matrix.os }}
          path: desktop.png
