on:
  workflow_call:
    inputs:
      updates:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(inputs.updates) }}
        os:
          - windows-2019
          # - windows-2022

    name: ${{ fromJSON(matrix.package).name }} ${{ fromJSON(matrix.package).version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      PackageName: ${{ fromJSON(matrix.package).name }}
      PackageVersion: ${{ fromJSON(matrix.package).version }}

    steps:
      - name: Configure chocolatey
        run: |
          choco feature enable -n=allowGlobalConfirmation
          choco feature disable -n=showDownloadProgress

      - name: Remove package if installed
        run: |
          if (choco list -r --local `"$Env:PackageName`") {
            choco uninstall `"$Env:PackageName`"
          }

      - name: Download Packages artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: Packages

      - name: Install package
        run: |
          choco install `"$Env:PackageName`" --version `"$Env:PackageVersion`" --source . --force --debug
          if ($LASTEXITCODE -in 1641, 3010) { exit 0 }
        working-directory: ${{ env.PackageName }}

      - name: Determine package information path
        id: information
        run: |
          $path = Join-Path $Env:ChocolateyInstall ".chocolatey/$Env:PackageName.$Env:PackageVersion"
          $path = $path -replace '\\', '/'
          Get-ChildItem $path
          "path=$path" >> $Env:GITHUB_OUTPUT

      - name: Upload Information artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Information ${{ fromJSON(matrix.package).name }} ${{ fromJSON(matrix.package).version }} on ${{ matrix.os }}
          path: ${{ steps.information.outputs.path }}

      - name: Uninstall package
        run: |
          choco uninstall `"$Env:PackageName`" --debug
          if ($LASTEXITCODE -in 1605, 1614, 1641, 3010) { exit 0 }
